//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OcrPlugin.App.Language.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class App {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal App() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OcrPlugin.App.Language.Resources.App", typeof(App).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akcja.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktywuj.
        /// </summary>
        public static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktywny.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj następny tytuł.
        /// </summary>
        public static string Add_Next_Title {
            get {
                return ResourceManager.GetString("Add_Next_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista dodanych koordynatów.
        /// </summary>
        public static string Added_CoordinatesList {
            get {
                return ResourceManager.GetString("Added_CoordinatesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz typ szablonu.
        /// </summary>
        public static string Chose_TemplateType {
            get {
                return ResourceManager.GetString("Chose_TemplateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miasto.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr Zlecenia.
        /// </summary>
        public static string ContractId {
            get {
                return ResourceManager.GetString("ContractId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stwórz.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ścieżka nie może być pusta..
        /// </summary>
        public static string CreateTemplateModelValidator_FilesDirectories_NotEmpty {
            get {
                return ResourceManager.GetString("CreateTemplateModelValidator_FilesDirectories_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szablon musi posiadać nazwę..
        /// </summary>
        public static string CreateTemplateModelValidator_Name_NotEmpty {
            get {
                return ResourceManager.GetString("CreateTemplateModelValidator_Name_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szablon musi zawierać przynajmiej jeden tytuł.
        /// </summary>
        public static string CreateTemplateModelValidator_Title_NotEmpty {
            get {
                return ResourceManager.GetString("CreateTemplateModelValidator_Title_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz typ szablonu..
        /// </summary>
        public static string CreateTemplateModelValidator_Type_NotEmpty {
            get {
                return ResourceManager.GetString("CreateTemplateModelValidator_Type_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dezaktywuj.
        /// </summary>
        public static string Deactivate {
            get {
                return ResourceManager.GetString("Deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa dłużnika.
        /// </summary>
        public static string DebtorName {
            get {
                return ResourceManager.GetString("DebtorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj się.
        /// </summary>
        public static string H1_LoginPage {
            get {
                return ResourceManager.GetString("H1_LoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienia.
        /// </summary>
        public static string H1_Settings {
            get {
                return ResourceManager.GetString("H1_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista szablonów.
        /// </summary>
        public static string H1_TemplateList {
            get {
                return ResourceManager.GetString("H1_TemplateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strona główna.
        /// </summary>
        public static string Header_Home {
            get {
                return ResourceManager.GetString("Header_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienia.
        /// </summary>
        public static string Header_Settings {
            get {
                return ResourceManager.GetString("Header_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szablony.
        /// </summary>
        public static string Header_TemplateList {
            get {
                return ResourceManager.GetString("Header_TemplateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyloguj.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dopasowane dane.
        /// </summary>
        public static string Matched_Data {
            get {
                return ResourceManager.GetString("Matched_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR-owane dane.
        /// </summary>
        public static string OCR_Data {
            get {
                return ResourceManager.GetString("OCR_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR.
        /// </summary>
        public static string OcrAllPage_Title {
            get {
                return ResourceManager.GetString("OcrAllPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ładowanie plików.
        /// </summary>
        public static string OcrPage_LoadingFiles {
            get {
                return ResourceManager.GetString("OcrPage_LoadingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strona OCR.
        /// </summary>
        public static string OcrPage_Title {
            get {
                return ResourceManager.GetString("OcrPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błędnie przetworzone.
        /// </summary>
        public static string OcrUpload_NumberOfBadOcr {
            get {
                return ResourceManager.GetString("OcrUpload_NumberOfBadOcr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poprawnie przetworzone.
        /// </summary>
        public static string OcrUpload_NumberOfGoodOcr {
            get {
                return ResourceManager.GetString("OcrUpload_NumberOfGoodOcr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wymagały korekty.
        /// </summary>
        public static string OcrUpload_NumberOfWarnOcr {
            get {
                return ResourceManager.GetString("OcrUpload_NumberOfWarnOcr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod pocztowy.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opcja.
        /// </summary>
        public static string Property {
            get {
                return ResourceManager.GetString("Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa.
        /// </summary>
        public static string Property_Name {
            get {
                return ResourceManager.GetString("Property_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jedno pole ID zamiast NIP, REGON, PESEL.
        /// </summary>
        public static string Public_Identifier {
            get {
                return ResourceManager.GetString("Public_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identyfikator.
        /// </summary>
        public static string PublicId {
            get {
                return ResourceManager.GetString("PublicId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SZABLON NIE ISTNIEJE.
        /// </summary>
        public static string Template_DontExists {
            get {
                return ResourceManager.GetString("Template_DontExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa szablnu.
        /// </summary>
        public static string Template_Name {
            get {
                return ResourceManager.GetString("Template_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tytuły szablonów.
        /// </summary>
        public static string Template_Titles {
            get {
                return ResourceManager.GetString("Template_Titles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy chcesz usunąć szablon?.
        /// </summary>
        public static string TemplateList_DoYouWantToRemoveTemplate {
            get {
                return ResourceManager.GetString("TemplateList_DoYouWantToRemoveTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ szablonu.
        /// </summary>
        public static string TemplateType {
            get {
                return ResourceManager.GetString("TemplateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podstawowy.
        /// </summary>
        public static string TemplateType_GeneralType {
            get {
                return ResourceManager.GetString("TemplateType_GeneralType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tytuł.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole musi być uzupełnione..
        /// </summary>
        public static string Validation_Field_Not_Empty {
            get {
                return ResourceManager.GetString("Validation_Field_Not_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartość.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tak.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
